/**
 * Created by Jordan on 19/07/2015.
 */

export var constants = {
    APP_URL: "http://localhost:9999",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOAD_USER: "LOAD_USER",
    LOAD_SELF: "LOAD_SELF",
    LOGOUT: "LOGOUT",
    LOGGED_IN: "LOGGED_IN",
    LOGGED_OUT: "LOGGED_OUT",
    API_WAIT: "API_WAIT",
    API_ERROR: "API_ERROR",
    API_FINISHED: "API_FINISHED",
    POST_MEAL: "POST_MEAL",
    LOAD_MEAL: "LOAD_MEAL",
    LOAD_MEAL_PICTURES: "LOAD_MEAL_PICTURES",
    QUERY_MEALS: "QUERY_MEALS",
    UPDATE_FILTERS: "UPDATE_FILTERS",
    LOAD_PICTURE: "LOAD_PICTURE"
};

